# Curbside: keep index.html in step with the app (ASCII only: PowerShell 5.1 reads BOM-less scripts as ANSI).
#   - the compliance list between <!-- CHECKS:BEGIN ... --> and <!-- CHECKS:END --> is rebuilt from the
#     criteria titles in parklet-checker.html (id c1..c15, num, title), so it cannot drift from the app
#   - the version between <!-- VERSION --> and <!-- /VERSION --> is the latest git tag
#   - the Supabase project ref between /*SBREF*/ and /*/SBREF*/ comes from the app's SUPABASE_URL
# Run after changing a check title, after tagging, or with -Check to report drift without writing.
param([switch]$Check)
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$enc = New-Object System.Text.UTF8Encoding $false
$app = [IO.File]::ReadAllText((Join-Path $Root 'parklet-checker.html'), $enc)
$idxPath = Join-Path $Root 'index.html'
$idx = [IO.File]::ReadAllText($idxPath, $enc)

$m = [regex]::Matches($app, "id:\s*'c(\d+)',\s*num:\s*'(\d+)',\s*title:\s*'((?:[^'\\]|\\.)*)'")
if ($m.Count -lt 15) { Write-Output ('expected at least 15 checks in the app, found ' + $m.Count); exit 1 }   # C01-C15 and, since Brief 21, C17-C19
$esc = { param($s) $s.Replace('\''', "'").Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;') }
$rows = ($m | ForEach-Object { '      <li data-check="c' + $_.Groups[2].Value + '"><span class="cno">C' + $_.Groups[2].Value + '</span> ' + (& $esc $_.Groups[3].Value) + '</li>' }) -join "`n"
$block = "<!-- CHECKS:BEGIN (generated by tools/sync-landing.ps1 from parklet-checker.html; do not edit) -->`n" + $rows + "`n      <!-- CHECKS:END -->"

$tag = ''
try { $tag = (& git -C $Root describe --tags --abbrev=0 2>$null) } catch {}
if (-not $tag) { $tag = 'untagged' }
$ref = ''
$u = [regex]::Match($app, "SUPABASE_URL\s*[:=]\s*'https://([a-z0-9]+)\.supabase\.co'")   # CONFIG.SUPABASE_URL (Brief 21 sec. 7)
if ($u.Success) { $ref = $u.Groups[1].Value }

$new = [regex]::Replace($idx, '<!-- CHECKS:BEGIN[\s\S]*?<!-- CHECKS:END -->', { param($x) $block })
$new = [regex]::Replace($new, '<!-- VERSION -->[\s\S]*?<!-- /VERSION -->', { param($x) '<!-- VERSION -->' + $tag + '<!-- /VERSION -->' })
if ($ref) { $new = [regex]::Replace($new, "/\*SBREF\*/'[a-z0-9]*'/\*/SBREF\*/", { param($x) "/*SBREF*/'" + $ref + "'/*/SBREF*/" }) }

if ($new -eq $idx) { Write-Output ('index.html is in step: ' + $m.Count + ' checks, version ' + $tag + ', project ref ' + $ref); exit 0 }
if ($Check) { Write-Output 'index.html has drifted from the app: run tools/sync-landing.ps1'; exit 2 }
[IO.File]::WriteAllText($idxPath, $new, $enc)
Write-Output ('index.html updated: ' + $m.Count + ' checks, version ' + $tag + ', project ref ' + $ref)
